### PR TITLE
Memory-fs is a required dependency, not a dev one.

### PR DESCRIPTION
**Pull request by bobylito**
I encountered this issue when trying to use this plugin. I had to add this dependency by hand.

### CODE REVIEW

**Comment by 10xjs** [comment]
@bobylito Good catch! I'll look into what's causing CI to fail here.

**Comment by vvo** [comment]
Ping @nealgranger, CI is failing because of eslint. https://github.com/metalabdesign/eslint-config-metalab/blob/master/package.json#L20 requires some peer dependencies you have to install too

**Comment by 10xjs** [comment]
Fixed in #4.

**Comment by bobylito** [comment]
:D

**Pull request closed without merging**
